### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by wdwmkr** [orzFly/woocommerce-gateway-ripple#1]
I have activated the plugin, put in my secret, I was able to complete a purchase but it never updated the order and in WooCommerce the order is marked as cancelled now.  When I go to http://wdwmkr.com/?woocommerce_ripplejson_secret=CRONSECRET I get the following error:

Fatal error: Uncaught exception 'Exception' with message 'JSON-RPC Error: no data. Please check your Ripple JSON-RPC settings.' in /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/lib/JsonRpcClient.php:120 Stack trace: #0 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/lib/JsonRpcClient.php(89): WooCommerca_Ripple_JsonRPCClient->curlPost('{"jsonrpc":"1.0...') #1 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(369): WooCommerca_Ripple_JsonRPCClient->__call('account_tx', Array) #2 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(369): WooCommerca_Ripple_JsonRPCClient->account_tx(Array) #3 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(411): WC_Gateway_Ripple->getAccountTx('rfrTnApj7qCMr2v...', -1) #4 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(474): WC_Gateway_Ripple->cronJob() #5 /home/content/40/112 in /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/lib/JsonRpcClient.php on line 120

**Comment by orzFly** [comment]
What kind of secret did you put? and in which fields?

**Comment by wdwmkr** [comment]
Good morning,  Once working I will totally donate. Adding attachment of my WooCommerce Settings.  I used my Ripple Wallet and the Secret Code that Ripple provided.  Was I suppose to make up a SECRET or use the Secret Code from Ripple?Attached is print screen of my setup.  For the Cron Secret I used my Ripple Secret. My sever does not have a terminal so for the Cron Job I created a PHP file with the following content and set to run every 15 minutes:<?php'curl http://wdwmkr.com/index.php?woocommerce_ripplejson_secret=HereIPutMyRippleSecret'?> I tried to two ways.  With my Ripple Secret and leaving the word SECRET.  If I leave the word SECRET and go to http://wdwmkr.com/?woocommerce_ripplejson_secret=SECRET it just takes me to my index.php page for my website.  If I try http://wdwmkr.com/?woocommerce_ripplejson_secret=HereIPutMyRippleSecret then I get the fatal error.  HereIPutMyRippleSecret means I put my actually Secret Code that Ripple provided me versus the text HereIPutMyRippleSecret-Sean

-------- Original Message --------
Subject: Re: [woocommerce-gateway-ripple] Fatal Error (#1)

**Comment by orzFly** [comment]
You don't have to use your Ripple secret. You just need to leave it a random string as only you know it.
If you set Cron Secret to `ABCDEFG`, you just need to run `http://wdwmkr.com/index.php?woocommerce_ripplejson_secret=ABCDEFG` every 15 minutes.

`curl` is just a tool to grab the page. There is no need to use another php wrapper to run it.

**Comment by orzFly** [comment]
WooCommerce will close timed-out orders. You can disable this or change to a longer time in “Products->Inventory->Hold Stock”.

**Comment by orzFly** [comment]
About the fatal error, I think maybe your server could not connect the Ripple server.

Since attachments from mail won't be posted. Can you reload it on GitHub?

**Comment by wdwmkr** [comment]
Good morning, Understood.  Forgive my lack of knowledge.  My GoDaddy has a Cron Manager that only allows me to point to a php file.  So I don't need to wrap the curl command in pho within the file for it to work?

-------- Original Message --------
Subject: Re: [woocommerce-gateway-ripple] Fatal Error (#1)

**Comment by orzFly** [comment]
Yes, you can just point to the "http://wdwmkr.com/index.php?woocommerce_ripplejson_secret=ABCDEFG” file in your Cron Manager of GoDaddy.
-- 
orzFly / Yeechan Lu

On July 19, 2014 at 20:00:14, wdwmkr (notifications@github.com) wrote:

Good morning, Understood.  Forgive my lack of knowledge.  My GoDaddy has a Cron Manager that only allows me to point to a php file.  So I don't need to wrap the curl command in pho within the file for it to work?

-------- Original Message --------
Subject: Re: [woocommerce-gateway-ripple] Fatal Error (#1)

**Comment by wdwmkr** [comment]
Trying to add png attachment

**Comment by orzFly** [comment]
GitHub don’t support email attachments. Could you please use a external service like imgur.com?
-- 
orzFly / Yeechan Lu

On July 19, 2014 at 20:14:46, wdwmkr (notifications@github.com) wrote:

Trying to add png attachment

**Comment by wdwmkr** [comment]
![ripple](https://cloud.githubusercontent.com/assets/8108048/3634799/b0391388-0f49-11e4-934b-bdd0e57947d4.png)

**Comment by wdwmkr** [comment]
So I changed the CRON Secret and updated my Cron job.  But when I go to http://wdwmkr.com/?woocommerce_ripplejson_secret=WDWMKR I still get the fatal error:  

 Fatal error: Uncaught exception 'Exception' with message 'JSON-RPC Error: no data. Please check your Ripple JSON-RPC settings.' in /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/lib/JsonRpcClient.php:120 Stack trace: #0 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/lib/JsonRpcClient.php(89): WooCommerca_Ripple_JsonRPCClient->curlPost('{"jsonrpc":"1.0...') #1 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(369): WooCommerca_Ripple_JsonRPCClient->__call('account_tx', Array) #2 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(369): WooCommerca_Ripple_JsonRPCClient->account_tx(Array) #3 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(411): WC_Gateway_Ripple->getAccountTx('rfrTnApj7qCMr2v...', -1) #4 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(474): WC_Gateway_Ripple->cronJob() #5 /home/content/40/112 in /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/lib/JsonRpcClient.php on line 120

**Comment by orzFly** [comment]
Can you try to choose "http://" for JSON-RPC SSL?

**Comment by wdwmkr** [comment]
I went into the WooCommerce Settings and set the JSON-RPC SSL to http:// instead of https://  But when I got to http://wdwmkr.com/?woocommerce_ripplejson_secret=WDWMKR I still get the fatal error.  The port is currently set to 51234  but I have also tried 5000 and 413.

-------- Original Message --------
Subject: Re: [woocommerce-gateway-ripple] Fatal Error (#1)

**Comment by wdwmkr** [comment]
If you want to email me directly (wdwmkr@wdwmkr.com) I can give you an admin login to the site in question?

-------- Original Message --------
Subject: Re: [woocommerce-gateway-ripple] Fatal Error (#1)

**Comment by orzFly** [comment]
I am sorry but there may be some problems with your hosting server. Can you make some changes to the code and put the output here?
1. In file woocommerce-ripple-json-rpc/lib/JsonRpcClient.php, change the following line (118):

``` php
$data = json_decode(curl_exec($ch), TRUE);
```

into

``` php
$raw = curl_exec($ch);
var_dump($raw);
$data = json_decode($raw, TRUE);
```
1. Navigate to the secret url in your browser.
2. Post the output here. (You should mask your privacy information)

**Comment by wdwmkr** [comment]
I made the requested changes.  Now it appears to say "bool(false) at the beginning of the error:

bool(false) Fatal error: Uncaught exception 'Exception' with message 'JSON-RPC Error: no data. Please check your Ripple JSON-RPC settings.' in /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/lib/JsonRpcClient.php:241 Stack trace: #0 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/lib/JsonRpcClient.php(177): WooCommerca_Ripple_JsonRPCClient->curlPost('{"jsonrpc":"1.0...') #1 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(369): WooCommerca_Ripple_JsonRPCClient->__call('account_tx', Array) #2 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(369): WooCommerca_Ripple_JsonRPCClient->account_tx(Array) #3 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(411): WC_Gateway_Ripple->getAccountTx('rfrTnApj7qCMr2v...', -1) #4 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(474): WC_Gateway_Ripple->cronJob() #5 /home/content/40/11 in /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/lib/JsonRpcClient.php on line 241

I tried with JSON-RPC SSL set to http:// and also https:// but same error in both cases-Seam

-------- Original Message --------
Subject: Re: [woocommerce-gateway-ripple] Fatal Error (#1)

**Comment by orzFly** [comment]
Can you change it into

``` php
$raw = curl_exec($ch);
if (FALSE === $raw)
{
    var_dump(array(curl_error($ch), curl_errno($ch)));
    throw new Exception(curl_error($ch), curl_errno($ch));
}
$data = json_decode($raw, TRUE);
```

and have a try again?

Thanks.

**Comment by wdwmkr** [comment]
I have made the requested change, tried with http:// and https:// and now get the error:  array(2) { [0]=> string(24) "couldn't connect to host" [1]=> int(7) } Fatal error: Uncaught exception 'Exception' with message 'couldn't connect to host' in /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/lib/JsonRpcClient.php:239 Stack trace: #0 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/lib/JsonRpcClient.php(177): WooCommerca_Ripple_JsonRPCClient->curlPost('{"jsonrpc":"1.0...') #1 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(369): WooCommerca_Ripple_JsonRPCClient->__call('account_tx', Array) #2 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(369): WooCommerca_Ripple_JsonRPCClient->account_tx(Array) #3 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(411): WC_Gateway_Ripple->getAccountTx('rfrTnApj7qCMr2v...', -1) #4 /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/ripple.php(474): WC_Gateway_Ripple->cronJob() #5 /home/content/40/11298740/html/wp-content/plugins/woocommerce-r in /home/content/40/11298740/html/wp-content/plugins/woocommerce-ripple-json-rpc/lib/JsonRpcClient.php on line 239

-------- Original Message --------
Subject: Re: [woocommerce-gateway-ripple] Fatal Error (#1)

**Comment by orzFly** [comment]
Well, it seems to be issues with GoDaddy.
- http://www.zen-cart.com/showthread.php?192688-(7)-couldn-t-connect-to-host-(problems-with-GoDaddy-hosting-on-Windows)
- http://stackoverflow.com/questions/9137206/make-a-php-curl-with-port-number

**Comment by wdwmkr** [comment]
Thank you I will take it up with GoDaddy and follow up once I find out their answer

**Comment by wdwmkr** [comment]
GoDaddy confirmed Linux hosting does not have access to port 51234 so reviewing options.  They advised dedicated hosting does allow access to that port.  Will follow up

**Comment by orzFly** [comment]
BTW thank you for letting me know there is a bug not reporting the errors in the plugin. I have updated it to 1.0.2.

This won't solve your problem but this can report errors now, without modifying the code.
